<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MDD4All.DME.ViewModels\src\MDD4All.DME.ViewModels\MDD4All.DME.ViewModels-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.DME.AssemblyTree\src\MDD4All.DME.AssemblyTree\MDD4All.DME.AssemblyTree-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.UI.Blazor\src\MDD4All.UI.Blazor\MDD4All.UI.Blazor-dev.csproj" />
    <ProjectReference Include="..\..\..\Synorvia.UI.BlazorComponents\src\Synorvia.UI.BlazorComponents\Synorvia.UI.BlazorComponents-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.Reflection.TypeAnalyzer\src\MDD4All.Reflection.TypeAnalyzer\MDD4All.Reflection.TypeAnalyzer-dev.csproj" />
  </ItemGroup>

</Project>
